/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javarpg.Game;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class InterfaceFrame extends javax.swing.JFrame {

    Game theGame;
    JPanel currentPanel;

    private MainMenuPanel theMainPanel;
    private DatabasePanel theDatabasePanel;
    private NewGamePanel theNewGamePanel;
    private GuildMenuPanel theGuildMenuPanel;

    //Boolean isVisible = false;
    /**
     * Creates new form Interface
     */
    public InterfaceFrame() {
        initComponents();
        setTitle("Java RPG");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //setUndecorated(true);

        //setVisible(true);
    }

    public InterfaceFrame(Game nuGame) {
        this();

        theGame = nuGame;
        //this.add(theGame.theMainPanel);
        //setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceFrame().setVisible(true);
            }
        });
    }

//    public boolean ChangeVisibility(boolean shouldIBeVisible){
//        this.isVisible = shouldIBeVisible;
//        return isVisible;
//    }
    public void setCurrentPanel(JPanel nuPanel) {
        if (currentPanel != null) {
            this.remove(currentPanel);
        }
        currentPanel = nuPanel;
        this.add(currentPanel);
        validate();//allows the next panel to actually show up
        repaint();//erases all graphics painted on previously
    }

    public void setMainMenuPanel(MainMenuPanel nuMainMenuPanel) {
        theMainPanel = nuMainMenuPanel;
    }

    public void setDatabasePanel(DatabasePanel nuDatabasePanel) {
        theDatabasePanel = nuDatabasePanel;
    }
    
    public void setNewGamePanel(NewGamePanel nuNewGamePanel){
        theNewGamePanel = nuNewGamePanel;
    }
    
    public void setGuildMenuPanel(GuildMenuPanel nuGuildMenuPanel){
        theGuildMenuPanel = nuGuildMenuPanel;
    }
    

    public void openMainMenuPanel() {
        setCurrentPanel(theMainPanel);
    }
    
    public void openGuildMenuPanel(){
        setCurrentPanel(theGuildMenuPanel);
    }

    public void openDatabasePanel() {
        setCurrentPanel(theDatabasePanel);
        theDatabasePanel.refresh();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
